services:
  - type: web
    name: fcpxml-generator
    runtime: python
    buildCommand: apt-get update && apt-get install -y ffmpeg && pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 1800 --workers 1
    plan: starter
